Extend report to consider users across different timezones
form3tech-oss/go-pagerduty-oncall-report pull request #41
Opened 2022-09-02 14:10 UTC by renato-araujo-form3

## Context

This PR introduces support for calculating the remuneration of on-call employees considering their timezones.

It is now possible to have a single more complex schedule with engineers located in different parts of the world and exclude the work schedule based on their timezones.

This featured required to add a new parameter (`defaultUserTimezone`) to define the default user timezone when not found in the PagerDuty API. This is to cover an edge case when there is a user listed in a PagerDuty schedule but for some reason was removed from the PagerDuty (i.e. left the company).

## Proof of Work

To exemplify one schedule will be created having the following parameters/configurations:
- Price per weekday: £16 (£1 per hour) | weekend/holiday: £32 (£2 per hour) 
- UK based engineer working from 09:00BST to 17:00BST
- Canadian based engineer working from 17:00BST (12:00EDT UTC -4) to 22:00BST (17:00EDT UTC -4)  
- <img width="1343" alt="Schedule layers" src="https://user-images.githubusercontent.com/100683264/189146767-fc507d21-573a-4f86-b91b-f7ae5bbb66a6.png">
- The report will be generated for 2 weeks, from 12th of September until 23rd of September, having the following schedule:
- <img width="947" alt="schedule" src="https://user-images.githubusercontent.com/100683264/189147581-455b40af-c16a-43c6-80ac-b9a2a9458bf1.png">

From the previous version without the timezone feature, the report generated will look like the image below:
- <img width="967" alt="old report" src="https://user-images.githubusercontent.com/100683264/189149339-2db7234e-3f32-495c-9663-3a345541252a.png">

The new version of the generated report:
- <img width="971" alt="new report" src="https://user-images.githubusercontent.com/100683264/189149672-621cd55a-af39-480d-8935-0bacaf968c29.png">

## Extra mile
- Small refactoring removing the API package dependency completely
- Fix known issue regarding users list command using pagination
  - This was required to avoid hundreds/thousands of API calls to fetch the user timezone, storing the user data in memory cache 
- Fixed a silent bug in the schedules list pagination that appears only after having 50+ schedules.

2022-09-14 13:17 UTC, jordan-van-dyk-form3 submitted a review, later dismissed

2022-09-14 14:46 UTC, wojciecholszewski-form3 commented on cmd/generate_report.go
> +	pricesInfo, err := Config.GetPricesInfo()
isn't it better to pass it as an argument to `generateReport` method?
one step forward towards getting rid of dependency on global `Config` variable

2022-09-14 15:03 UTC, wojciecholszewski-form3 commented on configuration/price.go
> +	excludedHours, _ := c.FindRotationExcludedHoursByDay("weekday")
why err is discarded here?

2022-09-14 15:04 UTC, wojciecholszewski-form3 commented on configuration/config.go
> +func (c *Configuration) FindRotationUserInfoByID(userID, userName string) (*RotationUser, error) {
weird change...
adding `userName` string only to print it to the console?

2022-09-14 15:07 UTC, wojciecholszewski-form3 commented on configuration/price.go
> +	excludedHours, _ = c.FindRotationExcludedHoursByDay("bankholiday")
again, why err is discarded?

2022-09-14 15:08 UTC, wojciecholszewski-form3 requested changes
Few questions left

2022-09-15 08:34 UTC, renato-araujo-form3 commented on configuration/config.go
> +func (c *Configuration) FindRotationUserInfoByID(userID, userName string) (*RotationUser, error) {
The reason for this change were:
- Removing the dependency of the API in the package that was used only to get the user name: https://github.com/form3tech-oss/go-pagerduty-oncall-report/blob/master/configuration/config.go#L117
- Not changing the format of the output, so since it was printing the name of the user in the console, and the information was already available I decided to use it as a parameter.

2022-09-15 08:36 UTC, renato-araujo-form3 commented on configuration/price.go
> +	excludedHours, _ := c.FindRotationExcludedHoursByDay("weekday")
I just moved this function from cmd package to the config package because it makes more sense to live there, but I didn't change any logic of it as you can see it [here](https://github.com/form3tech-oss/go-pagerduty-oncall-report/blob/master/cmd/generate_report.go#L439)

2022-09-15 08:36 UTC, renato-araujo-form3 commented on configuration/price.go
> +	excludedHours, _ = c.FindRotationExcludedHoursByDay("bankholiday")
see https://github.com/form3tech-oss/go-pagerduty-oncall-report/pull/41#discussion_r971693406

2022-09-15 08:36 UTC, renato-araujo-form3 commented on configuration/price.go
> +	excludedHours, _ = c.FindRotationExcludedHoursByDay("bankholiday")
see https://github.com/form3tech-oss/go-pagerduty-oncall-report/pull/41#discussion_r971695312

2022-09-15 08:46 UTC, renato-araujo-form3 commented on cmd/generate_report.go
> +	pricesInfo, err := Config.GetPricesInfo()
IMHO moving it to somewhere else to be injected as a parameter would not move one step forward from removing the dependency because of the dependency of the data structure. To effectively remove the dependency of the config it could be injected as an abstraction and keep it in the receiver, being beneficial also for testing purposes.

2022-09-15 11:08 UTC, wojciecholszewski-form3 commented on cmd/generate_report.go
> +	pricesInfo, err := Config.GetPricesInfo()
Abstraction is redundant here imho. Config is data struct with configuration values. What I am suggesting is simply passing it as an argument instead of referencing global variable. If you pass it as variable you don't need any abstraction to test it.

2022-09-15 11:09 UTC, wojciecholszewski-form3 commented on configuration/price.go
> +	excludedHours, _ := c.FindRotationExcludedHoursByDay("weekday")
I see, but it is awkward to see err being discarded. I would personally add err handling here.

2022-09-15 11:11 UTC, wojciecholszewski-form3 commented on configuration/price.go
> +	excludedHours, _ = c.FindRotationExcludedHoursByDay("bankholiday")
Adding err handling won't make it worse. I would personally add err handling here.

2022-09-15 11:57 UTC, renato-araujo-form3 commented on configuration/price.go
> +	excludedHours, _ := c.FindRotationExcludedHoursByDay("weekday")
I removed from the function because this error returning from `FindRotationExcludedHoursByDay` was not used anywhere.

2022-09-15 11:57 UTC, renato-araujo-form3 commented on configuration/price.go
> +	excludedHours, _ = c.FindRotationExcludedHoursByDay("bankholiday")
https://github.com/form3tech-oss/go-pagerduty-oncall-report/pull/41#discussion_r971892679

2022-09-15 11:57 UTC, renato-araujo-form3 commented on configuration/config.go
> +func (c *Configuration) FindRotationUserInfoByID(userID, userName string) (*RotationUser, error) {
Removed since it was unnecessary 👍

2022-09-15 12:55 UTC, wojciecholszewski-form3 approved these changes

2022-09-15 15:55 UTC, merged